---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-workshop-provider-config
  labels:
    app: k8s-workshop-provider
data:
  QUARKUS_DATASOURCE_JDBC_URL: "jdbc:mariadb://mariadb-service.mariadb.svc.cluster.local:3306/k8s-provider-service"
